ceylon_pj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from allauth.account import views

urlpatterns = [
    path('admin-sfinter-YppVSQN5mrdaPc5E/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('ceylontime.urls')),
]

# URL for media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ceylontime/urls.py
from django.urls import path

from . import views

app_name = 'ceylontime'
urlpatterns = [
    path('', views.DuringServeToGuestListViews.as_view(), name='home'),
    path('new/user/', views.UserCreateView.as_view(), name='user-create'),
    path('user/<int:pk>/', views.UserDetailView.as_view(), name='user-detail'),
    path('user/', views.UserListView.as_view(), name='user-list'),
    path('user/<int:pk>/update', views.UserUpdateView.as_view(), name='user-update'),
    path('user/<int:pk>/delete', views.UserDeleteView.as_view(), name='user-delete'),
    path('shop/<int:pk>/', views.ShopDetailView.as_view(), name='shop-detail'),
    path('guests/search/', views.search_guest, name='guest-search'),
    path('guests/search-by-keyword/', views.search_guest_by_keyword, name='guest-keyword-search'),
    path('guest/', views.GuestListView.as_view(), name='guest-list'),
    path('guest/<int:pk>/', views.GuestDetailView.as_view(), name='guest-detail'),
    path('guest/<int:pk>/user-update', views.UserUpdateGuestView.as_view(), name='user-update-guest'),
    path('mediator/<int:pk>/', views.MediatorDetailView.as_view(), name='mediator-detail'),
    path('history/', views.VisitHistoryListView.as_view(), name='visithistory-list'),
    path('history/<int:pk>/', views.VisitDetailView.as_view(), name='visit-detail'),
    path('new/history/', views.CreateVisitHistoryView.as_view(), name='new-visit'),
    path('history/<int:pk>/update/', views.UpdateVisitHistoryView.as_view(), name='update-visit'),
    path('history/<int:pk>/leave_shop/', views.UpdateLeaveShopView.as_view(), name='leave-shop'),
    path('history/<int:pk>/delete/', views.DeleteVisitHistoryView.as_view(), name='delete-visit'),
    path('dm-templates/', views.DMTemplateListView.as_view(), name='dm-template-list'),
    path('dm-templates/new/', views.DMTemplateCreateView.as_view(), name='dm-template-new'),
    path('dm-template/<int:pk>/update/', views.DMTemplateUpdateView.as_view(), name='dm-template-update'),
    path('dm-template/<int:pk>/delete/', views.DMTemplateDeleteView.as_view(), name='dm-template-delete'),
    path('dm-template/<int:pk>/', views.DMTemplateDetailView.as_view(), name='dm-template-detail'),
    path('dms/', views.DMListView.as_view(), name='dm-list'),
    path('dm/<int:pk>/', views.DMHistoryDetailView.as_view(), name='dm-detail'),
    path('dm/setup/', views.DMSetupView.as_view(), name='dm-setup'),
    path('dm/send/', views.DMSendView.as_view(), name='dm-send'),
]

# TODO create various edit views of User __ Accounts(Users) are made by people other than themselves, who should be logged in.
# TODO create edit(change) view of user models

ceylontime/models.py
import jaconv
from datetime import date, datetime
from django.db import models
from django.contrib.auth.models import User, Group
from django.urls import reverse


def to_zenkaku(string):

    if not string:
        return ''

    if not isinstance(string, str):
        return string

    return jaconv.h2z(string, digit=True, ascii=True)


def modify_guest_name():

    non_last_name_guests = Guest.objects.filter(last_name='')
    count = 0
    for guest in non_last_name_guests:
        name = guest.first_name
        if name:
            name = name.split()
        else:
            print("None first name guest: {}".format(guest))
            continue

        if len(name) <= 1:
            continue

        guest.last_name = name[0]
        guest.first_name = name[1]
        guest.save()
        print('{}{}'.format(guest.last_name, guest.first_name))
        count += 1

    print("Modified {} guest name".format(count))
    return


def modify_guest_kana():

    non_last_kana_guests = Guest.objects.filter(last_name_kana='')
    count = 0
    for non_last_kana_guest in non_last_kana_guests:
        kana = non_last_kana_guest.first_name_kana
        if kana:
            kana = kana.split()
        else:
            print("None first name kana guest: {}".format(non_last_kana_guest))
            continue

        if len(kana) <= 1:
            continue

        non_last_kana_guest.last_name_kana = kana[0]
        non_last_kana_guest.first_name_kana = kana[1]
        non_last_kana_guest.save()
        print('{} {}'.format(non_last_kana_guest.last_name_kana, non_last_kana_guest.first_name_kana))
        count += 1

    print("Modified {} guest kana".format(count))
    return


def modify_guest_kana_to_zenkaku():

    count = 0
    for g in Guest.objects.all():
        current_first_kana = g.first_name_kana
        current_last_kana = g.last_name_kana
        first_name_kana = to_zenkaku(g.first_name_kana)
        last_name_kana = to_zenkaku(g.last_name_kana)
        g.first_name_kana = first_name_kana
        g.last_name_kana = last_name_kana
        print("{} {} → {} {}".format(current_last_kana, current_first_kana, last_name_kana, first_name_kana))

        g.save()

        count += 1

    print("Modified {} guests kana convert to zenkaku".format(count))


class Shop(models.Model):
    shop_group = models.OneToOneField(Group, on_delete=models.DO_NOTHING, primary_key=True, verbose_name='店舗名（グループ名）,')
    phone = models.CharField('TEL', max_length=255)
    address1 = models.CharField('住所1', max_length=255)
    address2 = models.CharField('住所2', max_length=255)
    manager = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='shop_manager', null=True)

    class Meta:
        permissions = (
            # ("view_shop", "View shop"),
        )

    def __str__(self):
        return f'{self.shop_group}'


class Role(models.Model):
    name = models.CharField('役割', max_length=255)
    users = models.ManyToManyField(User)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='role_created_by')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='role_updated_by')

    def __str__(self):
        return self.name


class Mediator(models.Model):
    mediator = models.CharField('紹介元', max_length=255)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='mediator_created_by')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='mediator_updated_by')

    def __str__(self):
        return self.mediator

    class Meta:
        permissions = (
            # ("view_mediator", "View mediator"),
        )


class Guest(models.Model):

    NOT_CHOICE = 0
    MALE = 1
    FEMALE = 2
    GENDER_CHOICE = (
        (NOT_CHOICE, 'Not choice'),
        (MALE, '男'),
        (FEMALE, '女'),
    )

    # general information
    code = models.CharField('会員番号', max_length=20)
    first_name = models.CharField('名', max_length=20)
    first_name_kana = models.CharField('名（カナ）', max_length=40)
    last_name = models.CharField('氏', max_length=20)
    last_name_kana = models.CharField('氏（カナ）', max_length=40)
    birthday = models.DateField('生年月日', null=True, blank=True)
    gender = models.IntegerField('性別', choices=GENDER_CHOICE, default=NOT_CHOICE)
    phone = models.CharField('TEL', max_length=20, null=True, blank=True)
    cell_phone = models.CharField('携帯', max_length=20, null=True, blank=True)
    postal_code = models.CharField('郵便番号', max_length=20, null=True, blank=True)
    address1 = models.CharField('住所1', max_length=255, null=True, blank=True)
    address2 = models.CharField('住所2', max_length=255, null=True, blank=True)
    mail = models.EmailField('MAIL', null=True, blank=True)
    job = models.CharField('職業', max_length=100, null=True, blank=True)
    company = models.CharField('勤め先', max_length=100, null=True, blank=True)
    company_department = models.CharField('所属部署', max_length=100, null=True, blank=True)
    company_roll = models.CharField('役職', max_length=100, null=True, blank=True)
    company_address = models.CharField('勤務先住所', max_length=255, null=True, blank=True)
    company_tel = models.CharField('勤務先連絡先', max_length=20, null=True, blank=True)
    company_url = models.URLField('勤め先URL', max_length=256, null=True, blank=True)

    registration_date = models.DateField('ゲスト登録日', default=date.today)

    # gift information
    gift = models.ManyToManyField('Gift', related_name='guests', blank=True, verbose_name='ギフト情報')

    # contract information
    customer_of = models.ForeignKey(Mediator, on_delete=models.SET_NULL, null=True)
    related_guest = models.ManyToManyField('Guest', blank=True)
    access_token = models.CharField(max_length=255, unique=True, blank=True)

    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='guest_created_by')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='guest_updated_by')

    class Meta:
        permissions = (
            ('view_customerguest', 'View Guest who were invited Mediator'),
            # ('view_guest', 'View Guest Detail View'),
        )

    @property
    def latest_first_visithistory_set(self):
        return self.visithistory_set.order_by('-id')

    def get_absolute_url(self):
        return reverse('ceylontime:guest-detail', args=[self.pk])

    def __str__(self):
        return f'{self.last_name} {self.first_name}'


class GuestFamily(models.Model):

    guest = models.ForeignKey('Guest', on_delete=models.CASCADE, related_name='family', verbose_name='主会員')
    name = models.CharField('氏名', max_length=30)
    birthday = models.DateField('生年月日', null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='guest_family_created_by')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='guest_family_updated_by')


class VisitHistory(models.Model):

    # visit status
    NOT_VISIT = 0
    IN_VISIT = 1

    VISIT_STATUS = [
        (NOT_VISIT, '--'),
        (IN_VISIT, '来店中'),
    ]
    # service_pattern
    ALL_SERVICE = 0
    AWATOYO = 1
    NON_SERVICE = 2
    SERVICE_PATTERN = (
        (ALL_SERVICE, '全てサービス'),
        (AWATOYO, 'AWATOYO'),
        (NON_SERVICE, 'サービス無し'),
    )

    visit_status = models.IntegerField('来店状況', default=0, choices=VISIT_STATUS)
    guest_name = models.ForeignKey(Guest, on_delete=models.CASCADE)
    in_shop = models.ForeignKey(Shop, default=3, on_delete=models.CASCADE, verbose_name='来店店舗')
    visit_date = models.DateTimeField('来店日', auto_now_add=True)
    number_of_visitors = models.IntegerField('来店人数')
    payment = models.IntegerField('売上金額', default=0, blank=True, null=True)
    service_pattern = models.IntegerField('サービス区別', choices=SERVICE_PATTERN, default=NON_SERVICE)
    exist_reservation = models.BooleanField('予約有無', default=False)
    reservation_remark = models.CharField('予約情報備考', max_length=256, null=True, blank=True)
    salesperson = models.CharField('担当（ばんせい）', max_length=32, null=True, blank=True)
    comment = models.TextField('コメント', blank=True, default='')
    register_date = models.DateField('更新日時', auto_now=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='visit_history_created_by')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='visit_history_updated_by')

    def get_absolute_url(self):
        return reverse('ceylontime:visit-detail', args=[self.pk])

    def __str__(self):
        return '{} {}: {}, {}'.format(self.guest_name.last_name, self.guest_name.first_name, self.visit_date, self.payment)

MAX_SUBJECT_LENGTH = 1000
MAX_BODY_LENGTH = 20000

class DMTemplate(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name='テンプレート名',
        unique=True
    )
    subject = models.CharField(
        max_length=MAX_SUBJECT_LENGTH,
        verbose_name='件名'
    )
    body = models.TextField(
        max_length=MAX_BODY_LENGTH,
        verbose_name='本文'
    )
    test_mail = models.EmailField(
        'メールアドレス',

ceylontime/forms.py
from django import forms
from .models import DMTemplate

from django_summernote.widgets import SummernoteWidget


class DMTemplateCreateForm(forms.ModelForm):
    class Meta:
        model = DMTemplate
        fields = ['name', 'subject', 'body', 'test_mail']
        widgets = {
                'body': SummernoteWidget(attrs={'summernote': {'width': '100%'}}),
        }

ceylontime/templates/ceylontime/guest_detail.html
<!-- ceylontime/templates/ceylontime/guest_detail.html -->
{% extends 'base+qr.html' %}

{% load ceylontime_tags %}
{% load humanize %}

{% block css %}
<style>
table.visit-history {
  margin-top: 8px;
}
.section {
  margin-top: 1rem;
}
.section p {
  margin-left: 1rem;
}
.cancel-float {
  clear: both;
  padding-top: 1rem;
}
.generate-history {
  position: absolute;
  right: 30px;
}
</style>
{% endblock %}

{% block content %}
{% if perms.ceylontime.view_guest %}

<div>
  <div class="generate-history"><a href="{% url 'ceylontime:new-visit' %}?guest_pk={{ guest.pk }}"><button class="button">来店登録</button></a></div>
  <h1>会員番号<{{ guest.code }}>　{{ guest }}({{ guest.last_name_kana }} {{ guest.first_name_kana }})  様</h1>
  <h5 align="right">登録日：{{ guest.registration_date|date:'Y/m/d' }}</h5>

  <div>
    <h4>顧客情報</h4>
    {% include 'ceylontime/snippets/guest.html' %}
    {% if guest.family.all %}
    <table>ご家族：
      <tr>{% for family in guest.family.all %}
        <th>氏名</th>
        <th>生年月日</th>
      </tr>
      <tr>
        <td>{{ family.name }}</td>
        <td>{{ family.birthday }}</td>
      </tr>{% endfor %}
    </table>
    {% endif %}
  </div>
  <br>
  {% if perms.ceylontime.view_customerguest %}
  <div class="cancel-float">
    {% if guest.customer_of %}
    {% if perms.ceylontime.view_customerguest %}
    <h4>紹介元  </h4>
    <p><a href="{% url 'ceylontime:mediator-detail' guest.customer_of.pk %}">  {{ guest.customer_of }}</a></p>
    {% endif %}
    {% if guest.related_guest.all.exists %}
    <br/>
    <h4>登録ゲストリスト</h4>
    <table>
      <tr>
        <th>氏名</th>
        <th>登録日</th>
        <th>最終来店日</th>
        <th>来店回数</th>
      </tr>
      {% for relate in guest.related_guest.all %}
      <tr align="center">
        <td><a href="{{ relate.get_absolute_url }}">{{ relate }}</a></td>
        <td>{{ relate.registration_date|date:'Y/m/d' }}</td>
        {% if relate.visithistory_set.last %}
        <td>{{ relate.visithistory_set.last }}</td>
        {% else %}
        <td>来店履歴なし</td>
        {% endif %}
        <td>{{ relate.visithistory_set.count }} 回</td>
      </tr>
      {% endfor %}
    </table>
    {% endif %}
    {% endif %}
  </div>
  {% endif%}
  <div>
    <br>
    <table class="visit-history"><h4>来店履歴</h4>
      <tr>
        <th>来店日</th>
        <th>来店人数</th>
        <th>売上金額</th>
        <th>コメント</th>
      </tr>
      {% for history in guest.latest_first_visithistory_set %}
      <tr align="center">
        <td><a href="{{ history.get_absolute_url }}" >{{ history.visit_date|date:'Y/m/d H:m' }}</a></td>
        <td class="number">{{ history.number_of_visitors|intcomma }}</td>
        <td class="number">{{ history.payment|intcomma }}</td>
        <td>{{ history.comment }}</td>
      </tr>
      {% empty %}
      <tr align="center">
        <td colspan="4">来店履歴なし</td>
      </tr>
      {% endfor %}
      {% if perms.ceylontime.view_customerguest %}
      {% for rg in guest.related_guest.all %}
      {% for history in rg.latest_first_visithistory_set %}
      <tr>
        <td class="inner-title" colspan="4">ご紹介ゲスト様　：{{ rg.last_name}} {{ rg.first_name }}　様</td>
      </tr>
      <tr align="center">
        <td><a href="{{ history.get_absolute_url }}" >{{ history.visit_date|date:'Y/m/d H:m' }}</a></td>
        <td class="number">{{ history.number_of_visitors|intcomma }}</td>
        <td class="number">{{ history.payment|intcomma }}</td>
        <td>{{ history.comment }}</td>
      </tr>
      {% empty %}
      {% endfor %}
      {% endfor %}
      {% endif%}
    </table>
  </div>
  {% if guest.gift.all %}
  <div>
    <br>
    <h4>ギフト情報</h4>
    <table class="visit-history">
      <tr>
        <th>種類</th>
        <th>送付状況</th>
        <th>ギフト名</th>
        <th>送付年月</th>
      </tr>
      {% for gift in guest.gift.all %}
      <tr align="center">
        <td>{{ gift.get_gift_type_display }}</td>
        {% if gift.send_bool is True %}
        <td> ○ </td>
        {% else %}
        <td> × </td>
        {% endif %}
        {% if gift.gift %}
        <td>{{ gift.gift }}</td>
        {% else %}
        <td> - </td>
        {% endif %}
        {% if gift.send_date %}
        <td>{{ gift.send_date|date:'Y/m' }}</td>
        {% else %}
        <td> - </td>
        {% endif %}
      </tr>
      {% endfor %}
    </table>
  </div>
  {% endif %}
</div>
<br>
<a href="{% url 'ceylontime:user-update-guest' guest.pk %}"><input class="button" type="button" value="顧客情報更新"></a>
{% endif %}
{% endblock content %}

ceylontime/templates/ceylontime/guest_list.html
<!-- ceylontime/templates/ceylontime/guest_list.html -->
{% extends 'base+qr.html' %}

{% block css %}
<style>
.guest-list {
  margin-top: 16px;
}
.no-guests {
  margin-top: 16px;
}
</style>
{% endblock %}

{% block content %}
    <h1>Guest List</h1>

    {% if guest_list %}
    <table class="guest-list">
      <thead>
        <tr>
          <th>氏名</th>
          <th>カナ</th>
          <th>登録日</th>
          {% if perms.ceylontime.view_mediator %}<th>紹介者</th>{% endif %}
        </tr>
      </thead>
      <tbody>
        {% for guest in guest_list %}
        <tr>
          <td>
            <a href="{{ guest.get_absolute_url }}">{{ guest.last_name }} {{ guest.first_name }}</a>
          </td>
          <td>
            <a>{{ guest.last_name_kana }} {{ guest.first_name_kana }}</a>
          </td>
          <td>
            {{ guest.registration_date|date:'Y/m/d' }}
          </td>
          {% if perms.ceylontime.view_mediator %}
          <td>
              {% if guest.customer_of %}<a href="{% url 'ceylontime:mediator-detail' guest.customer_of.pk %}">{{ guest.customer_of.mediator }}</a>{% endif %}
          </td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </ul>
    {% else %}
    <div class="no-guests">ゲストの情報がありません。</div>
    {% endif %}

{% endblock content %}

ceylontime/templates/ceylontime/mediator_detail.html
<!-- ceylontime/templates/ceylontime/mediator_detail.html -->
{% extends 'base+qr.html' %}

{% block content %}
    <h1>紹介元情報</h1>
    <p>紹介元： {{ mediator }}</p>

    <table border=1>
      <tr>
        <th>紹介顧客名</th>
        <th>登録日</th>
      </tr>
      {% for cguest in mediator.guest_set.all %}
      <tr>
        <td><a href="{% url 'ceylontime:guest-detail' cguest.pk %}">{{ cguest }}</a></td>
        <td>{{ cguest.registration_date }}</td>
      </tr>
      {% endfor %}
    </table>

{% endblock content %}

ceylontime/templates/ceylontime/new_visithistory.html
<!-- ceylontime/templates/ceylontime/new_visithistory.html -->

{% extends 'base+qr.html' %}

{% block css %}
{% endblock %}

{% block content %}
    <h1>来店情報登録</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input class="button" type="submit" value="保存" />
      <a href="{% url 'ceylontime:home' %}"><input class="button" type="button" value="キャンセル"></a>
    </form>

{% endblock content %}

ceylontime/templates/ceylontime/shop_detail.html
{% extends 'base+qr.html' %}

{% block content %}

<div>
    <h4>No.{{ shop.pk }} 　所属名: {{ shop.shop_group }}</h4>
    <p>責任者（店長）： {{ shop.manager }}</p>
    <!-- TODO add Group members's List or Users related of -->
</div>

<div>
    {% if shop.visithistory_set %}
    <table class="guests-histories">
      <thead>
        <tr>
          <th>ステータス</th>
          <th>氏名</th>
          <th>来店日時</th>
        </tr>
      </thead>
      <tbody>
        {% for vh in shop.visithistory_set.all %}
        <tr>
          <td>{{ vh.visit_status }}</a></td>
          <td><a href="{{ vh.get_absolute_url }}">{{ vh.guest_name.last_name }} {{ vh.guest_name.first_name }}</a></td>
          <td><a href="{% url 'ceylontime:leave-shop' vh.pk %}">{{ vh.visit_date|date:'y/m/d' }}</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <div class="no-visiging-guest">現在、該当店舗には来店履歴はございません。</div>
    {% endif %}
</div>
{% endblock %}

ceylontime/templates/ceylontime/update_guest-visitstatus.html
<!-- ceylontime/templates/ceylontime/update_guest-visitstatus.html -->

{% extends 'base+qr.html' %}

{% block content %}
    <h1>来店情報更新</h1>
    <h2>{{ guest }}</h2>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input class="button" type="submit" value="来店/退店" />
    </form>

{% endblock content %}

ceylontime/templates/ceylontime/user_detail.html
<!-- ceylontime/templates/ceylontime/user_detail.html -->
{% extends 'base+qr.html' %}

{% block content %}
    <h1>社員情報</h1>
    <p>ID　　： {{ user.id }}</p>
    <p>社員名： {{ user }}</p>
    <p>所属　： {{ user.groups.all|join:", " }}</p>
    <p>役職名： {{ user.role_set.all|join:", " }}</p>

    <p>氏　　： {{ user.last_name }}</p>
    <p>名　　： {{ user.first_name }}</p>
    <p>メール： {{ user.email }}</p>

    <p class="button-container">
      <a class="button" href="{% url 'ceylontime:user-update' user.id %}">登録内容更新</a>
      <a class="button delete"  href="{% url 'ceylontime:user-delete' user.id %}">来店履歴削除</a>
    </p>
{% endblock content %}

ceylontime/templates/ceylontime/user_list.html
<!-- ceylontime/templates/ceylontime/user_list.html -->
{% extends 'base+qr.html' %}

{% block css %}
<style>
.guest-list {
  margin-top: 16px;
}
.no-guests {
  margin-top: 16px;
}
</style>
{% endblock %}

{% block content %}
    <h1>Staffs List</h1>

    {% if user_list %}
    <table class="user-list">
      <thead>
        <tr>
          <th>ID</th>
          <th>名前</th>
          <th>所属</th>
          <th>役職</th>
        </tr>
      </thead>
      <tbody>
        {% for user in user_list %}
        <tr>
          <td>
            <a>{{ user.id }}</a>
          </td>
          <td>
            <a href="{% url 'ceylontime:user-detail' user.id %}">{{ user }}</a>
          </td>
          <td>
            <a>{{ user.groups.all|join:", " }}</a>
          </td>
          <td>
            <a>{{ user.role_set.all|join:", "}}</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </ul>
    {% else %}
    <div class="no-guests">社員の情報がありません。</div>
    {% endif %}

{% endblock content %}

ceylontime/templates/ceylontime/user_update.html
<!-- ceylontime/templates/ceylontime/user_update.html -->

{% extends 'base+qr.html' %}

{% block css %}
{% endblock %}

{% block content %}
    <h1>社員情報更新</h1>
    <h2>{{ user.id }} : <a href="{% url 'ceylontime:user-detail' user.id %}">{{ user }}</a> 様</h2>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <p class="button-container">
        <input class="button" type="submit" value="更新" />
        <a href="{% url 'ceylontime:home' %}"><input class="button" type="button" value="キャンセル"></a>
      </p>
    </form>

{% endblock content %}

ceylontime/templates/ceylontime/visit_detail.html
<!-- ceylontime/templates/ceylontime/visit_detail.html -->
{% extends 'base+qr.html' %}

{% block css %}
<style>
p {
  line-height: 2.5rem;
}
p a {
  text-decoration: none;
}
</style>
{% endblock css %}

{% block content %}
    <h1>来店履歴詳細</h1>
    <p>ゲスト氏名： <a href="{% url 'ceylontime:guest-detail' visithistory.guest_name.id %}">{{ visithistory.guest_name }}</a></p>
    <p>ご来店店舗： {{ visithistory.in_shop }}</p>
    <p>来店日： {{ visithistory.visit_date|date:'Y/m/d' }}</p>
    <p>来店人数： {{ visithistory.number_of_visitors }}名</p>
    <p>売上金額： {% if visithistory.payment %}{{ visithistory.payment }}{% else %}---{% endif %}</p>
    <p>サービス区別： {{ visithistory.get_service_pattern_display }}</p>
    <p>予約有無： {% if visithistory.exist_reservation == 1 %}あり{% else %}なし{% endif %}</p>
    {% if visithistory.exist_reservation %}
    <p>予約情報備考： {{ visithistory.reservation_remark }}</p>
    {% endif %}
    {% if visithistory.guest_name.customer_of.pk == 3 %}
    <p>担当（ばんせい）： {% if visithistory.salesperson %}{{ visithistory.salesperson }}{% endif %}</p>
    {% endif %}
    <p>コメント： <br><small>
        {% if visithistory.comment %}
        {{ visithistory.comment | linebreaksbr  }}
        {% else %}コメントなし
        {% endif %}
    </small></p>

 {% if perms.ceylontime.change_visithistory %}
    <p class="button-container">
      <a class="button" href="{% url 'ceylontime:update-visit' visithistory.pk %}">登録内容更新</a>
      <a class="button delete"  href="{% url 'ceylontime:delete-visit' visithistory.pk %}">来店履歴削除</a>
    </p>
 {% endif %}

{% endblock content %}