ceylon_pj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from allauth.account import views

urlpatterns = [
    path('admin-sfinter-YppVSQN5mrdaPc5E/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('ceylontime.urls')),
]

# URL for media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ceylontime/urls.py
from django.urls import path

from . import views

app_name = 'ceylontime'
urlpatterns = [
    path('', views.DuringServeToGuestListViews.as_view(), name='home'),
    path('new/user/', views.UserCreateView.as_view(), name='user-create'),
    path('user/<int:pk>/', views.UserDetailView.as_view(), name='user-detail'),
    path('user/', views.UserListView.as_view(), name='user-list'),
    path('user/<int:pk>/update', views.UserUpdateView.as_view(), name='user-update'),
    path('user/<int:pk>/delete', views.UserDeleteView.as_view(), name='user-delete'),
    path('shop/<int:pk>/', views.ShopDetailView.as_view(), name='shop-detail'),
    path('guests/search/', views.search_guest, name='guest-search'),
    path('guests/search-by-keyword/', views.search_guest_by_keyword, name='guest-keyword-search'),
    path('guest/', views.GuestListView.as_view(), name='guest-list'),
    path('guest/<int:pk>/', views.GuestDetailView.as_view(), name='guest-detail'),
    path('guest/<int:pk>/user-update', views.UserUpdateGuestView.as_view(), name='user-update-guest'),
    path('mediator/<int:pk>/', views.MediatorDetailView.as_view(), name='mediator-detail'),
    path('history/', views.VisitHistoryListView.as_view(), name='visithistory-list'),
    path('history/<int:pk>/', views.VisitDetailView.as_view(), name='visit-detail'),
    path('new/history/', views.CreateVisitHistoryView.as_view(), name='new-visit'),
    path('history/<int:pk>/update/', views.UpdateVisitHistoryView.as_view(), name='update-visit'),
    path('history/<int:pk>/leave_shop/', views.UpdateLeaveShopView.as_view(), name='leave-shop'),
    path('history/<int:pk>/delete/', views.DeleteVisitHistoryView.as_view(), name='delete-visit'),
    path('dm-templates/', views.DMTemplateListView.as_view(), name='dm-template-list'),
    path('dm-templates/new/', views.DMTemplateCreateView.as_view(), name='dm-template-new'),
    path('dm-template/<int:pk>/update/', views.DMTemplateUpdateView.as_view(), name='dm-template-update'),
    path('dm-template/<int:pk>/delete/', views.DMTemplateDeleteView.as_view(), name='dm-template-delete'),
    path('dm-template/<int:pk>/', views.DMTemplateDetailView.as_view(), name='dm-template-detail'),
    path('dms/', views.DMListView.as_view(), name='dm-list'),
    path('dm/<int:pk>/', views.DMHistoryDetailView.as_view(), name='dm-detail'),
    path('dm/setup/', views.DMSetupView.as_view(), name='dm-setup'),
    path('dm/send/', views.DMSendView.as_view(), name='dm-send'),
]

# TODO create various edit views of User __ Accounts(Users) are made by people other than themselves, who should be logged in.
# TODO create edit(change) view of user models

ceylontime/forms.py
from django import forms
from .models import DMTemplate

from django_summernote.widgets import SummernoteWidget


class DMTemplateCreateForm(forms.ModelForm):
    class Meta:
        model = DMTemplate
        fields = ['name', 'subject', 'body', 'test_mail']
        widgets = {
                'body': SummernoteWidget(attrs={'summernote': {'width': '100%'}}),
        }

ceylontime/views.py
from django import forms
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, AccessMixin
from django.contrib.auth.models import User, Group
from django.core import mail
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.db.models import Value, Q, Count
from django.db.models.functions import Concat
from django.http import JsonResponse, Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.decorators.http import require_http_methods

from .templatetags import generate_history_row
from .models import Mediator, Guest, VisitHistory, Shop, Role, DMHistory, DMTemplate
from .forms import DMTemplateCreateForm

import json
import re

import logging
logger = logging.getLogger('django')

class AjaxableResponseMixin:
    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.is_ajax():
            data = {
                'pk': self.object.pk,
                'success_url': self.success_url
            }
            return JsonResponse(data)
        else:
            return response


# TODO create and CreateView, UpdateView, DetailView and DeleteView for User
class UserCreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = User
    second_model = Role
    template_name = 'ceylontime/user_create.html'
    fields = ['username', 'groups', 'first_name', 'last_name', 'email', 'role']
    success_url = reverse_lazy('ceylontime:home')


class UserDetailView(LoginRequiredMixin, generic.DetailView):
    model = User
    template_name = 'ceylontime/user_detail.html'

    # def get_context_data(self, **kwargs):
    #     context = super(UserDetailView, self).get_context_data(**kwargs)
    #     context['role'] = Role.objects.get(users=self.object)
    #     context['group'] = Group.objects.get(user=self.object)
    #     return context

    # def get_object(self, queryset=None):
    #     role = super(UserDetailView, self).get_object().role_set.get()
    #     group = super(UserDetailView, self).get_object().groups.get()
    #     return role


class UserListView(LoginRequiredMixin, generic.ListView):
    model = User
    template_name = 'ceylontime/user_list.html'
    paginate_by = 15

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        context['role'] = Role.objects.all()
        return context


class UserUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    model = User
    template_name = 'ceylontime/user_update.html'
    fields = ['username', 'groups', 'first_name', 'last_name', 'email']

    def get_success_url(self):
        return reverse('ceylontime:user-detail', args=[self.id])


class UserDeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    model = User
    template_name = 'ceylontime/user_delete.html'
    success_url = reverse_lazy('ceylontime:home')


class ShopDetailView(LoginRequiredMixin, generic.DetailView):
    model = Shop
    template_name = 'ceylontime/shop_detail.html'

    def get_object(self):
        obj = super().get_object()
        if self.request.user.has_perm('view_shop', obj):
            return obj
        else:
            raise Http404()


class GuestListView(LoginRequiredMixin, generic.ListView):
    model = Guest
    template_name = 'ceylontime/guest_list.html'
    paginate_by = 100
    # TODO add columns of reserviation and remote ordered??


class DuringServeToGuestListViews(LoginRequiredMixin, generic.ListView):
    model = VisitHistory
    template_name = 'ceylontime/home.html'

    def get_queryset(self):
        if self.request.user.groups.filter(name='executive').count() > 0:
            return VisitHistory.objects.filter(visit_status=VisitHistory.IN_VISIT).order_by('-visit_date')
        else:
            return VisitHistory.objects.filter(
                visit_status=VisitHistory.IN_VISIT,
                in_shop_id__in=[g.id for g in self.request.user.groups.all()]
            ).order_by('-visit_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tab_index'] = 0
        return context


class GuestDetailView(LoginRequiredMixin, generic.DetailView):
    model = Guest
    template_name = 'ceylontime/guest_detail.html'


# TODO: Implement permission
class UserUpdateGuestView(LoginRequiredMixin, generic.edit.UpdateView):
    model = Guest
    fields = (
        'birthday',
        'phone',
        'cell_phone',
        'postal_code',
        'address1',
        'address2',
        'mail',
        'job',
        'company',
        'company_department',
        'company_roll',
        'company_address',
        'company_tel',
    )
    template_name = 'ceylontime/user_update_guest.html'
    permission_required = ('ceylontime.change_guest')
    raise_exception = True

    def handle_no_permission(self):
        raise Http404


class MediatorDetailView(LoginRequiredMixin, PermissionRequiredMixin, AccessMixin, generic.DetailView):
    model = Mediator
    template_name = 'ceylontime/mediator_detail.html'
    permission_required = ('ceylontime.view_mediator')
    raise_exception = True

    def handle_no_permission(self):
        raise Http404


class VisitHistoryListView(LoginRequiredMixin, generic.ListView):
    model = VisitHistory
    template_name = 'ceylonitme/visithistory_list.html'

    def render_to_response(self, context, **kwargs):
        if self.request.is_ajax():
            return JsonResponse(self.get_ajax_json_data(context), **kwargs)
        else:
            return super(VisitHistoryListView, self).render_to_response(context, **kwargs)

    def get_ajax_json_data(self, context):
        result = []
        for h in self._get_histories():
            result.append(generate_history_row(h))
        return { 'tags': result }

    def get_queryset(self):
        if self.request.is_ajax():
            return None
        else:
            return self._get_histories()

    def _get_histories(self):
        if self.request.user.groups.filter(name='executive').count() > 0:
            history = VisitHistory.objects.all()
        else:
            history = VisitHistory.objects.filter(in_shop_id__in=[ g.id for g in self.request.user.groups.all() ])
        sort_order = self.request.GET.get('sort_order', 'register_date')
        desc = self.request.GET.get('desc', 'true').lower() == 'true'
        if sort_order == 'shop':
            history = history.order_by('{}in_shop__shop_group__name'.format('-' if desc else ''))
        elif sort_order == 'name':
            history = history.annotate(name=Concat('guest_name__last_name', Value(' '), 'guest_name__first_name')).order_by('{}name'.format('-' if desc else ''))
        else:
            history = history.order_by('{}{}'.format('-' if desc else '', sort_order))
        return history

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tab_index'] = 1
        return context


class VisitDetailView(LoginRequiredMixin, generic.DetailView):
    model = VisitHistory
    template_name = 'ceylontime/visit_detail.html'


class CreateVisitHistoryView(AjaxableResponseMixin, generic.edit.CreateView):
    model = VisitHistory
    template_name = 'ceylontime/new_visithistory.html'
    fields = ['guest_name', 'number_of_visitors', 'in_shop']
    success_url = reverse_lazy('ceylontime:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        guest = Guest.objects.filter(pk=self.request.GET.get('guest_pk')).first()
        if guest:
            context['form'].fields['guest_name'].initial = guest
        return context

    def form_valid(self, form):
        form.instance.visit_status = VisitHistory.IN_VISIT
        return super().form_valid(form)


class UpdateLeaveShopView(LoginRequiredMixin, generic.edit.UpdateView):
    model = VisitHistory
    fields = [
        'number_of_visitors',
        'payment',
        'service_pattern',
        'exist_reservation',
        'reservation_remark',
        'salesperson',
        'comment'
    ]
    template_name = 'ceylontime/update_leave_shop.html'
    success_url = reverse_lazy('ceylontime:home')

    def form_valid(self, form):
        payment = form.instance.payment
        if payment > 0:
            form.instance.visit_status = VisitHistory.NOT_VISIT
        # else payment = 0:
        # TODO set implement that display dialog caution 'Aren't you sure that the input amount is 0'
        # else payment = None:
        # TODO set implement that display dialog caution 'Please input the amount'

        return super().form_valid(form)

    def form_invalid(self, form):
        print(form.errors)
        return super().form_invalid(form)


class UpdateVisitHistoryView(LoginRequiredMixin, PermissionRequiredMixin, AccessMixin, generic.edit.UpdateView):
    model = VisitHistory
    fields = [
        'number_of_visitors',
        'payment',
        'service_pattern',
        'exist_reservation',
        'reservation_remark',
        'salesperson',
        'comment'
    ]
    template_name = 'ceylontime/update_visithistory.html'
    permission_required = ('ceylontime.change_visithistory')

ceylontime/templates/ceylontime/dm/template/create_form.html
{% extends 'ceylontime/dm/base.html' %}

{% block javascript_dm %}
<script>
  $(function(){
    var userEmailAddress = '{{ request.user.email }}';
    console.log(userEmailAddress);
    if (userEmailAddress) {
      $('input[name="test_mail"]').val(userEmailAddress);
    }
  });

</script>
{% endblock %}

{% block css_dm %}
<style>
input[name="subject"],
textarea[name="body"] {
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
}
.hint {
  background-color: #d8d8d8;
  color: #555;
  margin-top: -3px;
  padding: 8px 8px;
  font-size: 0.85em;
}
.hint .bold {
  font-weight: bolder;
}
</style>
{% endblock %}

{% block content_dm %}
<h1>新規DMテンプレート作成</h1>
<form method="post">
  {% csrf_token %}
  <table class="form-table">
    <tr>
      <td class="label">{{ form.name.label_tag }}</td>
      <td>{{ form.name }}{{ form.name.errors }}</td>
    </tr>
    <tr>
      <td class="label">{{ form.subject.label_tag }}</td>
      <td>
        {{ form.subject }}{{ form.subject.errors }}
        <div class="hint">
          <span class="bold">$氏名$</span> と入力すると、その部分を顧客の氏名に置き換えることができます。
        </div>
      </td>
    </tr>
    <tr>
      <td class="label">{{ form.body.label_tag }}</td>
      <td>
        {% spaceless %}
        {{ form.body }}
        <div class="hint">
          <span class="bold">$氏名$</span> と入力すると、その部分を顧客の氏名に置き換えることができます。
        </div>
        {{ form.body.errors }}
        {% endspaceless %}
      </td>
    </tr>
    <tr>
      <td class="label">{{ form.test_mail.label_tag }}</td>
      <td>
        {% spaceless %}
        <div class="test-mail">{{ form.test_mail }}</div>
        <div class="hint">
          テストメールを送るアドレスを入力してください。(デフォルト:ログインユーザーのアドレス)
        </div>
        {{ form.test_mail.errors }}
        {% endspaceless %}
      </td>
    </tr>
  </table>
  <div class="submit-button-wrapper">
    <input type="submit" class="button" value="作成" />
  </div>
</form>
{% endblock %}

ceylontime/templates/ceylontime/dm/template/delete_form.html
{% extends 'ceylontime/dm/base.html' %}

{% block javascript_dm %}
{% endblock %}

{% block css_dm %}
<style>
.confirmation-message {
  margin-top: 32px;
  font-size: 1.25em;
}
</style>
{% endblock %}

{% block content_dm %}
<h1>「{{ template.name }}」削除確認</h1>
<div class="confirmation-message">
  本当に削除してもよろしいですか？
</div>
<div class="button-wrapper">
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="button delete" value="削除" />
  </form>
</div>
{% endblock %}

ceylontime/templates/ceylontime/dm/template/detail.html
{% extends 'ceylontime/dm/base.html' %}

{% load ceylontime_tags %}

{% block javascript_dm %}
{% endblock %}

{% block css_dm %}
<style>
.header-link {
  margin-bottom: 16px;
}
table {
  margin-top: 32px;
  table-layout: fixed;
}
table td.label {
  width: 5em;
  white-space: nowrap;
  text-align: right;
}
table .body-wrapper {
  overflow-x: auto;
  white-space: pre;
  overflow-wrap: normal;
}
</style>
{% endblock %}

{% block content_dm %}
<div class="header-link">
  <a href="{% url 'ceylontime:dm-template-list' %}">一覧に戻る</a>
</div>
<h1>{{ template.name }}</h1>
<table>
  <tr>
    <td class="label">件名:</td><td>{{ template.subject }}</td>
  </tr>
  <tr>
    <td class="label">本文:</td>
    <td>
      <div class="body-wrapper">
        {{ template.body| safe }}
      </div>
    </td>
  </tr>
  <tr>
    <td class="label">作成者:</td>
    <td>{% if template.created_by %}{{ template.created_by }}{% else %}---{% endif %}</td>
  </tr>
  <tr>
    <td class="label">作成日時:</td>
    <td>{{ template.created_at|date:'Y/m/d H:i' }}</td>
  </tr>
  <tr>
    <td class="label">更新者:</td>
    <td>{% if template.updated_by %}{{ template.updated_by }}{% else %}---{% endif %}</td>
  </tr>
  <tr>
    <td class="label">更新日時:</td>
    <td>{{ template.updated_at|date:'Y/m/d H:i' }}</td>
  </tr>
</table>
<div class="button-wrapper">
  {% spaceless %}
  <a href="{% url 'ceylontime:dm-template-update' template.id %}" class="button">編集</a>
  <a href="{% url 'ceylontime:dm-template-delete' template.id %}" class="button delete">削除</a>
  {% endspaceless %}
</div>
{% endblock %}

ceylontime/templates/ceylontime/dm/template/list.html
{% extends 'ceylontime/dm/base.html' %}

{% load humanize %}

{% block javascript_dm %}
{% endblock %}

{% block css_dm %}
<style>
.templates {
  font-size: 0.9em;
}
.templates.top-margin {
  margin-top: 32px;
}
.count {
  font-weight: bolder;
  margin-top: 32px;
  margin-bottom: 8px;
}
.no-templates {
  text-align: center;
}
</style>
{% endblock %}

{% block content_dm %}
<div class="title clearfix">
  <div class="h1 float-left">DMテンプレート一覧</div>
  <div class="float-right">
    <a class="button" href="{% url 'ceylontime:dm-template-new' %}">新規作成</a>
  </div>
</div>
{% if templates.count > 0 %}
<div class="count">全{{ templates.count|intcomma }}件</div>
{% endif %}
<table class="templates{% if templates.count == 0 %} top-margin{% endif %}">
  <tr>
    <th></th>
    <th>テンプレート名</th>
    <th>作成者</th>
    <th>作成日時</th>
    <th>更新者</th>
    <th>更新日時</th>
    <th></th>
  </tr>
  {% for t in templates %}
  <tr>
    <td>{{ forloop.counter }}</td>
    <td>
      <a href="{% url 'ceylontime:dm-template-detail' t.id %}">{{ t.name }}</a>
    </td>
    <td>{% if t.created_by %}{{ t.created_by }}{% else %}---{% endif %}</td>
    <td>{{ t.created_at|date:'Y/m/d H:i' }}</td>
    <td>{% if t.updated_by %}{{ t.updated_by }}{% else %}---{% endif %}</td>
    <td>{{ t.updated_at|date:'Y/m/d H:i' }}</td>
    <td class="control">
      {% spaceless %}
      <a href="{% url 'ceylontime:dm-template-update' t.id %}" class="button with-right-button">編集</a>
      <a href="{% url 'ceylontime:dm-template-delete' t.id %}" class="button delete with-left-button">削除</a>
      {% endspaceless %}
    </td>
  </tr>
  {% empty %}
  <tr><td class="no-templates" colspan="7">DMテンプレートはありません</td></tr>
  {% endfor %}
</table>
{% endblock %}

ceylontime/templates/ceylontime/dm/template/update_form.html
{% extends 'ceylontime/dm/base.html' %}

{% block javascript_dm %}
{% endblock %}

{% block css_dm %}
<style>
input[name="subject"],
textarea[name="body"] {
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
}
.hint {
  background-color: #d8d8d8;
  color: #555;
  margin-top: -3px;
  padding: 8px 8px;
  font-size: 0.85em;
}
.hint .bold {
  font-weight: bolder;
}
</style>
{% endblock %}

{% block content_dm %}
<h1>DMテンプレート編集</h1>
<form method="post">
  {% csrf_token %}
  <table class="form-table">
    <tr>
      <td class="label">{{ form.name.label_tag }}</td>
      <td>{{ form.name }}{{ form.name.errors }}</td>
    </tr>
    <tr>
      <td class="label">{{ form.subject.label_tag }}</td>
      <td>
        {{ form.subject }}{{ form.subject.errors }}
        <div class="hint">
          <span class="bold">$氏名$</span> と入力すると、その部分を顧客の氏名に置き換えることができます。
        </div>
      </td>
    </tr>
    <tr>
      <td class="label">{{ form.body.label_tag }}</td>
      <td>
        {% spaceless %}
        {{ form.body }}
        <div class="hint">
          <span class="bold">$氏名$</span> と入力すると、その部分を顧客の氏名に置き換えることができます。
        </div>
        {{ form.body.errors }}
        {% endspaceless %}
      </td>
    </tr>
    <tr>
      <td class="label">{{ form.test_mail.label_tag }}</td>
      <td>
        {% spaceless %}
        <div class="test-mail">{{ form.test_mail }}</div>
        <div class="hint">
          テストメールを送るアドレスを入力してください。
        </div>
        {{ form.test_mail.errors }}
        {% endspaceless %}
      </td>
    </tr>
  </table>
  <div class="submit-button-wrapper">
    <input type="submit" class="button" value="更新" />
  </div>
</form>
{% endblock %}