ceylon_pj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from allauth.account import views

urlpatterns = [
    path('admin-sfinter-YppVSQN5mrdaPc5E/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('ceylontime.urls')),
]

# URL for media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ceylontime/urls.py
from django.urls import path

from . import views

app_name = 'ceylontime'
urlpatterns = [
    path('', views.DuringServeToGuestListViews.as_view(), name='home'),
    path('new/user/', views.UserCreateView.as_view(), name='user-create'),
    path('user/<int:pk>/', views.UserDetailView.as_view(), name='user-detail'),
    path('user/', views.UserListView.as_view(), name='user-list'),
    path('user/<int:pk>/update', views.UserUpdateView.as_view(), name='user-update'),
    path('user/<int:pk>/delete', views.UserDeleteView.as_view(), name='user-delete'),
    path('shop/<int:pk>/', views.ShopDetailView.as_view(), name='shop-detail'),
    path('guests/search/', views.search_guest, name='guest-search'),
    path('guests/search-by-keyword/', views.search_guest_by_keyword, name='guest-keyword-search'),
    path('guest/', views.GuestListView.as_view(), name='guest-list'),
    path('guest/<int:pk>/', views.GuestDetailView.as_view(), name='guest-detail'),
    path('guest/<int:pk>/user-update', views.UserUpdateGuestView.as_view(), name='user-update-guest'),
    path('mediator/<int:pk>/', views.MediatorDetailView.as_view(), name='mediator-detail'),
    path('history/', views.VisitHistoryListView.as_view(), name='visithistory-list'),
    path('history/<int:pk>/', views.VisitDetailView.as_view(), name='visit-detail'),
    path('new/history/', views.CreateVisitHistoryView.as_view(), name='new-visit'),
    path('history/<int:pk>/update/', views.UpdateVisitHistoryView.as_view(), name='update-visit'),
    path('history/<int:pk>/leave_shop/', views.UpdateLeaveShopView.as_view(), name='leave-shop'),
    path('history/<int:pk>/delete/', views.DeleteVisitHistoryView.as_view(), name='delete-visit'),
    path('dm-templates/', views.DMTemplateListView.as_view(), name='dm-template-list'),
    path('dm-templates/new/', views.DMTemplateCreateView.as_view(), name='dm-template-new'),
    path('dm-template/<int:pk>/update/', views.DMTemplateUpdateView.as_view(), name='dm-template-update'),
    path('dm-template/<int:pk>/delete/', views.DMTemplateDeleteView.as_view(), name='dm-template-delete'),
    path('dm-template/<int:pk>/', views.DMTemplateDetailView.as_view(), name='dm-template-detail'),
    path('dms/', views.DMListView.as_view(), name='dm-list'),
    path('dm/<int:pk>/', views.DMHistoryDetailView.as_view(), name='dm-detail'),
    path('dm/setup/', views.DMSetupView.as_view(), name='dm-setup'),
    path('dm/send/', views.DMSendView.as_view(), name='dm-send'),
]

# TODO create various edit views of User __ Accounts(Users) are made by people other than themselves, who should be logged in.
# TODO create edit(change) view of user models

ceylontime/models.py
import jaconv
from datetime import date, datetime
from django.db import models
from django.contrib.auth.models import User, Group
from django.urls import reverse


def to_zenkaku(string):

    if not string:
        return ''

    if not isinstance(string, str):
        return string

    return jaconv.h2z(string, digit=True, ascii=True)


def modify_guest_name():

    non_last_name_guests = Guest.objects.filter(last_name='')
    count = 0
    for guest in non_last_name_guests:
        name = guest.first_name
        if name:
            name = name.split()
        else:
            print("None first name guest: {}".format(guest))
            continue

        if len(name) <= 1:
            continue

        guest.last_name = name[0]
        guest.first_name = name[1]
        guest.save()
        print('{}{}'.format(guest.last_name, guest.first_name))
        count += 1

    print("Modified {} guest name".format(count))
    return


def modify_guest_kana():

    non_last_kana_guests = Guest.objects.filter(last_name_kana='')
    count = 0
    for non_last_kana_guest in non_last_kana_guests:
        kana = non_last_kana_guest.first_name_kana
        if kana:
            kana = kana.split()
        else:
            print("None first name kana guest: {}".format(non_last_kana_guest))
            continue

        if len(kana) <= 1:
            continue

        non_last_kana_guest.last_name_kana = kana[0]
        non_last_kana_guest.first_name_kana = kana[1]
        non_last_kana_guest.save()
        print('{} {}'.format(non_last_kana_guest.last_name_kana, non_last_kana_guest.first_name_kana))
        count += 1

    print("Modified {} guest kana".format(count))
    return


def modify_guest_kana_to_zenkaku():

    count = 0
    for g in Guest.objects.all():
        current_first_kana = g.first_name_kana
        current_last_kana = g.last_name_kana
        first_name_kana = to_zenkaku(g.first_name_kana)
        last_name_kana = to_zenkaku(g.last_name_kana)
        g.first_name_kana = first_name_kana
        g.last_name_kana = last_name_kana
        print("{} {} → {} {}".format(current_last_kana, current_first_kana, last_name_kana, first_name_kana))

        g.save()

        count += 1

    print("Modified {} guests kana convert to zenkaku".format(count))


class Shop(models.Model):
    shop_group = models.OneToOneField(Group, on_delete=models.DO_NOTHING, primary_key=True, verbose_name='店舗名（グループ名）,')
    phone = models.CharField('TEL', max_length=255)
    address1 = models.CharField('住所1', max_length=255)
    address2 = models.CharField('住所2', max_length=255)
    manager = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='shop_manager', null=True)

    class Meta:
        permissions = (
            # ("view_shop", "View shop"),
        )

    def __str__(self):
        return f'{self.shop_group}'


class Role(models.Model):
    name = models.CharField('役割', max_length=255)
    users = models.ManyToManyField(User)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='role_created_by')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='role_updated_by')

    def __str__(self):
        return self.name


class Mediator(models.Model):
    mediator = models.CharField('紹介元', max_length=255)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='mediator_created_by')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='mediator_updated_by')

    def __str__(self):
        return self.mediator

    class Meta:
        permissions = (
            # ("view_mediator", "View mediator"),
        )


class Guest(models.Model):

    NOT_CHOICE = 0
    MALE = 1
    FEMALE = 2
    GENDER_CHOICE = (
        (NOT_CHOICE, 'Not choice'),
        (MALE, '男'),
        (FEMALE, '女'),
    )

    # general information
    code = models.CharField('会員番号', max_length=20)
    first_name = models.CharField('名', max_length=20)
    first_name_kana = models.CharField('名（カナ）', max_length=40)
    last_name = models.CharField('氏', max_length=20)
    last_name_kana = models.CharField('氏（カナ）', max_length=40)
    birthday = models.DateField('生年月日', null=True, blank=True)
    gender = models.IntegerField('性別', choices=GENDER_CHOICE, default=NOT_CHOICE)
    phone = models.CharField('TEL', max_length=20, null=True, blank=True)
    cell_phone = models.CharField('携帯', max_length=20, null=True, blank=True)
    postal_code = models.CharField('郵便番号', max_length=20, null=True, blank=True)
    address1 = models.CharField('住所1', max_length=255, null=True, blank=True)
    address2 = models.CharField('住所2', max_length=255, null=True, blank=True)
    mail = models.EmailField('MAIL', null=True, blank=True)
    job = models.CharField('職業', max_length=100, null=True, blank=True)
    company = models.CharField('勤め先', max_length=100, null=True, blank=True)
    company_department = models.CharField('所属部署', max_length=100, null=True, blank=True)
    company_roll = models.CharField('役職', max_length=100, null=True, blank=True)
    company_address = models.CharField('勤務先住所', max_length=255, null=True, blank=True)
    company_tel = models.CharField('勤務先連絡先', max_length=20, null=True, blank=True)
    company_url = models.URLField('勤め先URL', max_length=256, null=True, blank=True)

    registration_date = models.DateField('ゲスト登録日', default=date.today)

    # gift information
    gift = models.ManyToManyField('Gift', related_name='guests', blank=True, verbose_name='ギフト情報')

    # contract information
    customer_of = models.ForeignKey(Mediator, on_delete=models.SET_NULL, null=True)
    related_guest = models.ManyToManyField('Guest', blank=True)
    access_token = models.CharField(max_length=255, unique=True, blank=True)

    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='guest_created_by')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='guest_updated_by')

    class Meta:
        permissions = (
            ('view_customerguest', 'View Guest who were invited Mediator'),
            # ('view_guest', 'View Guest Detail View'),
        )

    @property
    def latest_first_visithistory_set(self):
        return self.visithistory_set.order_by('-id')

    def get_absolute_url(self):
        return reverse('ceylontime:guest-detail', args=[self.pk])

    def __str__(self):
        return f'{self.last_name} {self.first_name}'


class GuestFamily(models.Model):

    guest = models.ForeignKey('Guest', on_delete=models.CASCADE, related_name='family', verbose_name='主会員')
    name = models.CharField('氏名', max_length=30)
    birthday = models.DateField('生年月日', null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='guest_family_created_by')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='guest_family_updated_by')


class VisitHistory(models.Model):

    # visit status
    NOT_VISIT = 0
    IN_VISIT = 1

    VISIT_STATUS = [
        (NOT_VISIT, '--'),
        (IN_VISIT, '来店中'),
    ]
    # service_pattern
    ALL_SERVICE = 0
    AWATOYO = 1
    NON_SERVICE = 2
    SERVICE_PATTERN = (
        (ALL_SERVICE, '全てサービス'),
        (AWATOYO, 'AWATOYO'),
        (NON_SERVICE, 'サービス無し'),
    )

    visit_status = models.IntegerField('来店状況', default=0, choices=VISIT_STATUS)
    guest_name = models.ForeignKey(Guest, on_delete=models.CASCADE)
    in_shop = models.ForeignKey(Shop, default=3, on_delete=models.CASCADE, verbose_name='来店店舗')
    visit_date = models.DateTimeField('来店日', auto_now_add=True)
    number_of_visitors = models.IntegerField('来店人数')
    payment = models.IntegerField('売上金額', default=0, blank=True, null=True)
    service_pattern = models.IntegerField('サービス区別', choices=SERVICE_PATTERN, default=NON_SERVICE)
    exist_reservation = models.BooleanField('予約有無', default=False)
    reservation_remark = models.CharField('予約情報備考', max_length=256, null=True, blank=True)
    salesperson = models.CharField('担当（ばんせい）', max_length=32, null=True, blank=True)
    comment = models.TextField('コメント', blank=True, default='')
    register_date = models.DateField('更新日時', auto_now=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='visit_history_created_by')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='visit_history_updated_by')

    def get_absolute_url(self):
        return reverse('ceylontime:visit-detail', args=[self.pk])

    def __str__(self):
        return '{} {}: {}, {}'.format(self.guest_name.last_name, self.guest_name.first_name, self.visit_date, self.payment)

MAX_SUBJECT_LENGTH = 1000
MAX_BODY_LENGTH = 20000

class DMTemplate(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name='テンプレート名',
        unique=True
    )
    subject = models.CharField(
        max_length=MAX_SUBJECT_LENGTH,
        verbose_name='件名'
    )
    body = models.TextField(
        max_length=MAX_BODY_LENGTH,
        verbose_name='本文'
    )
    test_mail = models.EmailField(
        'メールアドレス',

ceylontime/forms.py
from django import forms
from .models import DMTemplate

from django_summernote.widgets import SummernoteWidget


class DMTemplateCreateForm(forms.ModelForm):
    class Meta:
        model = DMTemplate
        fields = ['name', 'subject', 'body', 'test_mail']
        widgets = {
                'body': SummernoteWidget(attrs={'summernote': {'width': '100%'}}),
        }

ceylontime/templates/ceylontime/snippets/guest.html
<style>
input[type="text"], input[type="email"] {
  width: 100%
}
.label  {
  width: 28%;
}
.value {
  value: 72%;
}
.table_section {
  float: left;
  width: 100%;
  &:after {
    content: "";
    display: block;
    clear: both;
  }
}
.table_section table, .table_section td {
  border: none;
}

input[type="text"], input[type="email"] {
  width: 100%
}
.table_section-left, .table_section-right {
  float: left;
  width: 50%
}
.table_section-right {
  float: right;
}

</style>

<div class="table_section">
  <div class="table_section-left">
    <table><h4>基本情報</h4>
      {% if perms.ceylontime.view_customerguest %}
      {% if guest.phone %}
      <tr>
        <td class="label">TEL&ensp;&ensp;:</td>
        <td class="value">{{ guest.phone }}</td>
      </tr>
      {% endif %}
      {% if guest.cell_phone %}
      <tr>
        <td class="label">携帯&ensp;&ensp;:</td>
        <td class="value">{{ guest.cell_phone }}</td>
      </tr>
      {% endif %}
      {% if guest.mail %}
      <tr>
        <td class="label">EMail&ensp;&ensp;:</td>
        <td class="value">{{ guest.mail }}</td>
      </tr>
      {% endif %}
      {% if guest.gender %}
      <tr>
        <td class="label">性別&ensp;&ensp;:</td>
        <td class="value">{{ guest.get_gender_display }}</td>
      </tr>
      {% endif %}
      {% endif %}
      {% if guest.birthday %}
      <tr>
        <td class="label">生年月日&ensp;&ensp;:</td>
        <td class="value">{{ guest.birthday }}</td>
      </tr>
      {% endif %}
      {% if perms.ceylontime.view_customerguest %}
      {% if guest.postal_code %}
      <tr>
        <td class="label">郵便番号&ensp;&ensp;:</td>
        <td class="value">{{ guest.postal_code }}</td>
      </tr>
      {% endif %}
      {% if guest.address2 %}
      <tr>
        <td class="label">住所1&ensp;&ensp;:</td>
        <td class="value">{{ guest.address1 }}</td>
      </tr>
      <tr>
        <td class="label">住所2&ensp;&ensp;:</td>
        <td class="value">{{ guest.address2 }}</td>
      </tr>
      {% else %}
      <tr>
        <td class="label">住所&ensp;&ensp;:</td>
        <td class="value">{{ guest.address1 }}</td>
      </tr>
      {% endif %}
      {% if guest.job %}
      <tr>
        <td class="label">職業&ensp;&ensp;:</td>
        <td class="value">{{ guest.job }}</td>
      </tr>
      {% endif %}
      {% endif %}
    </table>
  </div>
  <div class="table_section-right">
    {% if perms.ceylontime.view_customerguest %}
    {% if guest.company %}
    <table><h4>勤務先情報</h4>
      {% if guest.company %}
      <tr>
        <td class="label">勤務先&ensp;&ensp;:</td>
        {% if guest.company_url %}
        <td class="value"><a target="_blank" href="{{ guest.company_url }}">{{ guest.company }}</a></td>
        {% else %}
        <td class="value">{{ guest.company }}</td>
        {% endif %}
      </tr>
      {% endif %}
      {% if guest.company_department %}
      <tr>
        <td class="label">部署&ensp;&ensp;:</td>
        <td class="value">{{ guest.company_department }}</td>
      </tr>
      {% endif %}
      {% if guest.company_roll %}
      <tr>
        <td class="label">役職&ensp;&ensp;:</td>
        <td class="value">{{ guest.company_roll }}</td>
      </tr>
      {% endif %}
      {% if guest.company_address %}
      <tr>
        <td class="label">住所&ensp;&ensp;:</td>
        <td class="value">{{ guest.company_address }}</td>
      </tr>
      {% endif %}
      {% if guest.company_tel %}
      <tr>
        <td class="label">TEL&ensp;&ensp;:</td>
        <td class="value">{{ guest.company_tel }}</td>
      </tr>
      {% endif %}
    </table>
    {% endif %}
    {% endif %}
  </div>
</div>

ceylontime/templates/ceylontime/snippets/guest_form.html
<style>
table,table td {
  border: none;
}
input[type="text"], input[type="email"] {
  width: 100%
}
table td {
  text-align: right;
}
.label  {
  width: 32%;
}
.value {
  value: 68%;
}
.table_section {
  float: left;
  width: 100%;
  &:after {
    content: "";
    display: block;
    clear: both;
  }
}
.table_section-left, .table_section-right {
  float: left;
  width: 49%
}
.table_section-right {
  float: right;
  margin-right: 3px;
}


</style>

<div class="table_section">
  <div class="table_section-left">
    <table><h4>基本情報</h4>
      {% if guest.phone %}
      <tr>
        <td class="label">{{ guest.phone.label_tag }}</td>
        <td class="value">{{ guest.phone }}</td>
      </tr>
      {% endif %}
      {% if guest.cell_phone %}
      <tr>
        <td class="label">{{ guest.cell_phone.label_tag }}</td>
        <td class="value">{{ guest.cell_phone }}</td>
      </tr>
      {% endif %}
      {% if guest.mail %}
      <tr>
        <td class="label">{{ guest.mail.label_tag }}</td>
        <td class="value">{{ guest.mail }}</td>
      </tr>
      {% endif %}
      {% if guest.gender %}
      <tr>
        <td class="label">{{ guest.gender.label_tag }}</td>
        <td class="value">{{ guest.get_gender_display }}</td>
      </tr>
      {% endif %}
      {% if guest.birthday %}
      <tr>
        <td class="label">{{ guest.birthday.label_tag }}</td>
        <td class="value">{{ guest.birthday }}</td>
      </tr>
      {% endif %}
      {% if guest.postal_code %}
      <tr>
        <td class="label">{{ guest.postal_code.label_tag }}</td>
        <td class="value">{{ guest.postal_code }}</td>
      </tr>
      {% endif %}
      <tr>
        <td class="label">{{ guest.address1.label_tag }}</td>
        <td class="value">{{ guest.address1 }}</td>
      </tr>
      {% if guest.address2 %}
      <tr>
        <td class="label">{{ guest.address2.label_tag }}</td>
        <td class="value">{{ guest.address2 }}</td>
      </tr>
      {% endif %}
      {% if guest.job %}
      <tr>
        <td class="label">{{ guest.job.label_tag }}</td>
        <td class="value">{{ guest.job }}</td>
      </tr>
      {% endif %}
    </table>
  </div>
  <div class="table_section-right">
    {% if guest.company %}
    <table><h4>勤務先情報</h4>
      {% if guest.company %}
      <tr>
        <td class="label">{{ guest.company.label_tag }}</td>
        <td class="value">{{ guest.company }}</td>
      </tr>
      {% endif %}
      {% if guest.company_department %}
      <tr>
        <td class="label">{{ guest.company_department.label_tag }}</td>
        <td class="value">{{ guest.company_department }}</td>
      </tr>
      {% endif %}
      {% if guest.company_roll %}
      <tr>
        <td class="label">{{ guest.company_roll.label_tag }}</td>
        <td class="value">{{ guest.company_roll }}</td>
      </tr>
      {% endif %}
      {% if guest.company_address %}
      <tr>
        <td class="label">{{ guest.company_address.label_tag }}</td>
        <td class="value">{{ guest.company_address }}</td>
      </tr>
      {% endif %}
      {% if guest.company_tel %}
      <tr>
        <td class="label">{{ guest.company_tel.label_tag }}</td>
        <td class="value">{{ guest.company_tel }}</td>
      </tr>
      {% endif %}
    </table>
  </div>
{% endif %}
</div>

ceylontime/templates/ceylontime/snippets/tab.html
<style>
.tab-container {
  border-bottom: 1px solid #aaa;
}
.tab-container ul li {
  display: inline-block;
  border-bottom: 3px solid transparent;
}
.tab-container ul li.selected {
  border-bottom: 3px solid #f9ca24;
}
.tab-container ul li a {
  text-decoration: none;
  padding: 16px 32px 12px;
  display: inline-block;
  color: #777;
  font-size: 1.2rem;
}
.tab-container ul li:hover a {
  background-color: #f9f9f9;
}
.tab-container ul li:not(.selected):hover {
  border-bottom: 3px solid #f9f9f9;
}
.tab-container ul li.selected a {
  color: #333;
}
</style>
<div class="tab-container">
  {% spaceless %}
  <ul>
    <li class="in_visit{% if tab_index == 0 %} selected{% endif %}"><a href="{% url 'ceylontime:home' %}">来店中のゲスト</a></li>
    <li class="history{% if tab_index == 1 %} selected{% endif %}"><a href="{% url 'ceylontime:visithistory-list' %}">来店履歴</a></li>
  </ul>
  {% endspaceless %}
</div>

ceylontime/templates/ceylontime/snippets/visit_history_form.html
<script>
$(function() {
  checkStatus();
  $('input[name="exist_reservation"]').on('click', checkStatus);
});
function checkStatus() {
  var $checkbox = $('input[name="exist_reservation"]');
  var $field = $("#optional_fields");
  if( $checkbox.prop('checked') ){
    $field.show();
  }
  else {
    $field.hide();
  }
}
</script>
<style>
  .form-table {
    margin-bottom: 16px;
  }
  .form-table,
  .form-table tr,
  .form-table td {
    border: none;
  }
  .form-table td.label {
    width: 1%;
    white-space: nowrap;
  }
</style>
<h2>{{ visithistory.in_shop }} : <a href="{% url 'ceylontime:guest-detail' visithistory.guest_name.id %}">{{ visithistory.guest_name }}</a> 様</h2>
<form action="" method="post">
  {% csrf_token %}
  <table class="form-table">
    <tbody>
      {% for field in form %}
      {% if field.name == 'reservation_remark' %}
      <tr id='optional_fields'>
        <td class="label">{{ field.label_tag }}</td><td>{{ field }}{{ field.error }}</td>
      </tr>
      {% elif field.name == 'salesperson' and fields.customer_of.pk == 3 %}
      {% else %}
      <tr>
        <td class="label">{{ field.label_tag }}</td><td>{{ field }}{{ field.error }}</td>
      </tr>
      {% endif %}
      {% endfor %}
    </tbody>
  </table>
  <input class="button" type="submit" value="登録" />
  <a href="{% url 'ceylontime:home' %}"><input class="button" type="button" value="キャンセル"></a>
</form>