ceylon_pj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from allauth.account import views

urlpatterns = [
    path('admin-sfinter-YppVSQN5mrdaPc5E/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('ceylontime.urls')),
]

# URL for media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ceylontime/urls.py
from django.urls import path

from . import views

app_name = 'ceylontime'
urlpatterns = [
    path('', views.DuringServeToGuestListViews.as_view(), name='home'),
    path('new/user/', views.UserCreateView.as_view(), name='user-create'),
    path('user/<int:pk>/', views.UserDetailView.as_view(), name='user-detail'),
    path('user/', views.UserListView.as_view(), name='user-list'),
    path('user/<int:pk>/update', views.UserUpdateView.as_view(), name='user-update'),
    path('user/<int:pk>/delete', views.UserDeleteView.as_view(), name='user-delete'),
    path('shop/<int:pk>/', views.ShopDetailView.as_view(), name='shop-detail'),
    path('guests/search/', views.search_guest, name='guest-search'),
    path('guests/search-by-keyword/', views.search_guest_by_keyword, name='guest-keyword-search'),
    path('guest/', views.GuestListView.as_view(), name='guest-list'),
    path('guest/<int:pk>/', views.GuestDetailView.as_view(), name='guest-detail'),
    path('guest/<int:pk>/user-update', views.UserUpdateGuestView.as_view(), name='user-update-guest'),
    path('mediator/<int:pk>/', views.MediatorDetailView.as_view(), name='mediator-detail'),
    path('history/', views.VisitHistoryListView.as_view(), name='visithistory-list'),
    path('history/<int:pk>/', views.VisitDetailView.as_view(), name='visit-detail'),
    path('new/history/', views.CreateVisitHistoryView.as_view(), name='new-visit'),
    path('history/<int:pk>/update/', views.UpdateVisitHistoryView.as_view(), name='update-visit'),
    path('history/<int:pk>/leave_shop/', views.UpdateLeaveShopView.as_view(), name='leave-shop'),
    path('history/<int:pk>/delete/', views.DeleteVisitHistoryView.as_view(), name='delete-visit'),
    path('dm-templates/', views.DMTemplateListView.as_view(), name='dm-template-list'),
    path('dm-templates/new/', views.DMTemplateCreateView.as_view(), name='dm-template-new'),
    path('dm-template/<int:pk>/update/', views.DMTemplateUpdateView.as_view(), name='dm-template-update'),
    path('dm-template/<int:pk>/delete/', views.DMTemplateDeleteView.as_view(), name='dm-template-delete'),
    path('dm-template/<int:pk>/', views.DMTemplateDetailView.as_view(), name='dm-template-detail'),
    path('dms/', views.DMListView.as_view(), name='dm-list'),
    path('dm/<int:pk>/', views.DMHistoryDetailView.as_view(), name='dm-detail'),
    path('dm/setup/', views.DMSetupView.as_view(), name='dm-setup'),
    path('dm/send/', views.DMSendView.as_view(), name='dm-send'),
]

# TODO create various edit views of User __ Accounts(Users) are made by people other than themselves, who should be logged in.
# TODO create edit(change) view of user models

ceylontime/models.py
import jaconv
from datetime import date, datetime
from django.db import models
from django.contrib.auth.models import User, Group
from django.urls import reverse


def to_zenkaku(string):

    if not string:
        return ''

    if not isinstance(string, str):
        return string

    return jaconv.h2z(string, digit=True, ascii=True)


def modify_guest_name():

    non_last_name_guests = Guest.objects.filter(last_name='')
    count = 0
    for guest in non_last_name_guests:
        name = guest.first_name
        if name:
            name = name.split()
        else:
            print("None first name guest: {}".format(guest))
            continue

        if len(name) <= 1:
            continue

        guest.last_name = name[0]
        guest.first_name = name[1]
        guest.save()
        print('{}{}'.format(guest.last_name, guest.first_name))
        count += 1

    print("Modified {} guest name".format(count))
    return


def modify_guest_kana():

    non_last_kana_guests = Guest.objects.filter(last_name_kana='')
    count = 0
    for non_last_kana_guest in non_last_kana_guests:
        kana = non_last_kana_guest.first_name_kana
        if kana:
            kana = kana.split()
        else:
            print("None first name kana guest: {}".format(non_last_kana_guest))
            continue

        if len(kana) <= 1:
            continue

        non_last_kana_guest.last_name_kana = kana[0]
        non_last_kana_guest.first_name_kana = kana[1]
        non_last_kana_guest.save()
        print('{} {}'.format(non_last_kana_guest.last_name_kana, non_last_kana_guest.first_name_kana))
        count += 1

    print("Modified {} guest kana".format(count))
    return


def modify_guest_kana_to_zenkaku():

    count = 0
    for g in Guest.objects.all():
        current_first_kana = g.first_name_kana
        current_last_kana = g.last_name_kana
        first_name_kana = to_zenkaku(g.first_name_kana)
        last_name_kana = to_zenkaku(g.last_name_kana)
        g.first_name_kana = first_name_kana
        g.last_name_kana = last_name_kana
        print("{} {} → {} {}".format(current_last_kana, current_first_kana, last_name_kana, first_name_kana))

        g.save()

        count += 1

    print("Modified {} guests kana convert to zenkaku".format(count))


class Shop(models.Model):
    shop_group = models.OneToOneField(Group, on_delete=models.DO_NOTHING, primary_key=True, verbose_name='店舗名（グループ名）,')
    phone = models.CharField('TEL', max_length=255)
    address1 = models.CharField('住所1', max_length=255)
    address2 = models.CharField('住所2', max_length=255)
    manager = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='shop_manager', null=True)

    class Meta:
        permissions = (
            # ("view_shop", "View shop"),
        )

    def __str__(self):
        return f'{self.shop_group}'


class Role(models.Model):
    name = models.CharField('役割', max_length=255)
    users = models.ManyToManyField(User)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='role_created_by')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='role_updated_by')

    def __str__(self):
        return self.name


class Mediator(models.Model):
    mediator = models.CharField('紹介元', max_length=255)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='mediator_created_by')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='mediator_updated_by')

    def __str__(self):
        return self.mediator

    class Meta:
        permissions = (
            # ("view_mediator", "View mediator"),
        )


class Guest(models.Model):

    NOT_CHOICE = 0
    MALE = 1
    FEMALE = 2
    GENDER_CHOICE = (
        (NOT_CHOICE, 'Not choice'),
        (MALE, '男'),
        (FEMALE, '女'),
    )

    # general information
    code = models.CharField('会員番号', max_length=20)
    first_name = models.CharField('名', max_length=20)
    first_name_kana = models.CharField('名（カナ）', max_length=40)
    last_name = models.CharField('氏', max_length=20)
    last_name_kana = models.CharField('氏（カナ）', max_length=40)
    birthday = models.DateField('生年月日', null=True, blank=True)
    gender = models.IntegerField('性別', choices=GENDER_CHOICE, default=NOT_CHOICE)
    phone = models.CharField('TEL', max_length=20, null=True, blank=True)
    cell_phone = models.CharField('携帯', max_length=20, null=True, blank=True)
    postal_code = models.CharField('郵便番号', max_length=20, null=True, blank=True)
    address1 = models.CharField('住所1', max_length=255, null=True, blank=True)
    address2 = models.CharField('住所2', max_length=255, null=True, blank=True)
    mail = models.EmailField('MAIL', null=True, blank=True)
    job = models.CharField('職業', max_length=100, null=True, blank=True)
    company = models.CharField('勤め先', max_length=100, null=True, blank=True)
    company_department = models.CharField('所属部署', max_length=100, null=True, blank=True)
    company_roll = models.CharField('役職', max_length=100, null=True, blank=True)
    company_address = models.CharField('勤務先住所', max_length=255, null=True, blank=True)
    company_tel = models.CharField('勤務先連絡先', max_length=20, null=True, blank=True)
    company_url = models.URLField('勤め先URL', max_length=256, null=True, blank=True)

    registration_date = models.DateField('ゲスト登録日', default=date.today)

    # gift information
    gift = models.ManyToManyField('Gift', related_name='guests', blank=True, verbose_name='ギフト情報')

    # contract information
    customer_of = models.ForeignKey(Mediator, on_delete=models.SET_NULL, null=True)
    related_guest = models.ManyToManyField('Guest', blank=True)
    access_token = models.CharField(max_length=255, unique=True, blank=True)

    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='guest_created_by')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='guest_updated_by')

    class Meta:
        permissions = (
            ('view_customerguest', 'View Guest who were invited Mediator'),
            # ('view_guest', 'View Guest Detail View'),
        )

    @property
    def latest_first_visithistory_set(self):
        return self.visithistory_set.order_by('-id')

    def get_absolute_url(self):
        return reverse('ceylontime:guest-detail', args=[self.pk])

    def __str__(self):
        return f'{self.last_name} {self.first_name}'


class GuestFamily(models.Model):

    guest = models.ForeignKey('Guest', on_delete=models.CASCADE, related_name='family', verbose_name='主会員')
    name = models.CharField('氏名', max_length=30)
    birthday = models.DateField('生年月日', null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='guest_family_created_by')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='guest_family_updated_by')


class VisitHistory(models.Model):

    # visit status
    NOT_VISIT = 0
    IN_VISIT = 1

    VISIT_STATUS = [
        (NOT_VISIT, '--'),
        (IN_VISIT, '来店中'),
    ]
    # service_pattern
    ALL_SERVICE = 0
    AWATOYO = 1
    NON_SERVICE = 2
    SERVICE_PATTERN = (
        (ALL_SERVICE, '全てサービス'),
        (AWATOYO, 'AWATOYO'),
        (NON_SERVICE, 'サービス無し'),
    )

    visit_status = models.IntegerField('来店状況', default=0, choices=VISIT_STATUS)
    guest_name = models.ForeignKey(Guest, on_delete=models.CASCADE)
    in_shop = models.ForeignKey(Shop, default=3, on_delete=models.CASCADE, verbose_name='来店店舗')
    visit_date = models.DateTimeField('来店日', auto_now_add=True)
    number_of_visitors = models.IntegerField('来店人数')
    payment = models.IntegerField('売上金額', default=0, blank=True, null=True)
    service_pattern = models.IntegerField('サービス区別', choices=SERVICE_PATTERN, default=NON_SERVICE)
    exist_reservation = models.BooleanField('予約有無', default=False)
    reservation_remark = models.CharField('予約情報備考', max_length=256, null=True, blank=True)
    salesperson = models.CharField('担当（ばんせい）', max_length=32, null=True, blank=True)
    comment = models.TextField('コメント', blank=True, default='')
    register_date = models.DateField('更新日時', auto_now=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='visit_history_created_by')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='visit_history_updated_by')

    def get_absolute_url(self):
        return reverse('ceylontime:visit-detail', args=[self.pk])

    def __str__(self):
        return '{} {}: {}, {}'.format(self.guest_name.last_name, self.guest_name.first_name, self.visit_date, self.payment)

MAX_SUBJECT_LENGTH = 1000
MAX_BODY_LENGTH = 20000

class DMTemplate(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name='テンプレート名',
        unique=True
    )
    subject = models.CharField(
        max_length=MAX_SUBJECT_LENGTH,
        verbose_name='件名'
    )
    body = models.TextField(
        max_length=MAX_BODY_LENGTH,
        verbose_name='本文'
    )
    test_mail = models.EmailField(
        'メールアドレス',

ceylontime/forms.py
from django import forms
from .models import DMTemplate

from django_summernote.widgets import SummernoteWidget


class DMTemplateCreateForm(forms.ModelForm):
    class Meta:
        model = DMTemplate
        fields = ['name', 'subject', 'body', 'test_mail']
        widgets = {
                'body': SummernoteWidget(attrs={'summernote': {'width': '100%'}}),
        }

ceylontime/templates/base+qr.html
{% extends 'base_generic.html' %}

{% load static %}

{% block javascript_generic %}
<script>
  {% if request.user.is_authenticated %}
  var csrftoken = '{{ csrf_token }}';
  {% else %}
  var csrftoken = null;
  {% endif %}
</script>
<script type="text/javascript" src="{% static 'ceylontime/js/ajax-common.js' %}"></script>
<script type="text/javascript" src="{% static 'ceylontime/js/date.format.js' %}"></script>
<script>
  var incomingString = '';
  var scanFunc = function(e) {
    if (e.which !== 0 && e.key.length == 1) {
      e.stopPropagation();
      e.preventDefault();
      if (incomingString.length == 0) {
        setTimeout(function() {
          incomingString = '';
        }, 500);
      }
      incomingString += e.key;
      // TODO magic value for access token length: 24
      if (incomingString.length == 24) {
        getUser(incomingString);
      }
    }
  };
  var numPadFunc = function(e) {
    if (e.keyCode >= 48 && e.keyCode <= 57) {
      var num = String(e.keyCode - 48);
      $('.numpad .num.' + num).addClass('num-flash');
      setTimeout(function() {
        $('.numpad .num.' + num).removeClass('num-flash');
      }, 250);
      inputNum(num);
    } else if (e.keyCode == 8) {
      del();
      $('.numpad .del').addClass('ctrl-flash');
      setTimeout(function() {
        $('.numpad .del').removeClass('ctrl-flash');
      }, 250);
    } else if (e.keyCode == 67) {
      clear();
      $('.numpad .clear').addClass('ctrl-flash');
      setTimeout(function() {
        $('.numpad .clear').removeClass('ctrl-flash');
      }, 250);
    }
  };
  $(function() {
    $('#qr_scan_status').on('click', function() {
      incomingString = '';
      $(document).on('keydown', scanFunc);
      $(document).off('keydown', numPadFunc);
      $('<div/>').attr('id', 'qr_scan_background').appendTo('body');
      $('<div/>')
        .html(
          '<div>QRコードリーダーにカードをかざしてください</div>' +
          '<div style="margin-top: 32px;"><span class="button close-button">終了</span></div>'
        )
        .appendTo('#qr_scan_background');
      $('#qr_scan_background .close-button').on('click', function(e) {
        e.preventDefault();
        $(document).off('keydown', scanFunc);
        $('#qr_scan_background').remove();
      });
    });
    $('.footer-button.ok, .footer-button.cancel').on('click', function(e) {
      e.preventDefault();
      $(document).off('keydown', numPadFunc);
      $('#result_dialog, .result-bg').removeClass('show');
      setTimeout(function() {
        $('#result_dialog, .result-bg').hide();
        $('.numpad .number-of-visitor .value').html('1');
        $('#result_dialog #family_list').empty();
        $('#result_dialog').removeClass('with-family');
      }, 600);
      if ($(this).hasClass('ok')) {
        createVisitHistory($('#result').data('guest_id'));
      }
    });
  });
  $(function() {
    $('.numpad .num').on('click', function(e) {
      e.preventDefault();
      var num = $(this).html();
      inputNum(num);
    });
    $('.numpad .del').on('click', function(e) {
      e.preventDefault();
      del();
    });
    $('.numpad .clear').on('click', function(e) {
      e.preventDefault();
      clear();
    });
    $('.numpad .ok').on('click', function(e) {
      e.preventDefault();
      enter();
    });
  });
  function inputNum(num) {
    var current = $('.numpad .number-of-visitor .value').html();
    if (current == '0' || $('.numpad').hasClass('init')) current = '';
    if (current.length < 5) {
      $('.numpad .number-of-visitor .value').html(current + num);
    }
    $('.numpad').removeClass('init');
  }
  function del() {
    var current = $('.numpad .number-of-visitor .value').html();
    var deletedNum = current.substring(0, current.length - 1);
    if (deletedNum.length == 0) deletedNum = '0'
    $('.numpad .number-of-visitor .value').html(deletedNum);
  }
  function clear() {
    $('.numpad .number-of-visitor .value').html('0');
  }
  function enter() {
    var numberOfVisitor = $('.numpad .number-of-visitor .value').html();
    alert(numberOfVisitor);
    $('.numpad .number-of-visitor .value').html('1');
  }

  function getUser(token) {
    $('#qr_scan_background').remove();
    $(document).off('keydown', scanFunc);
    incomingString = '';
    $.ajax({
      type: 'GET',
      url: '/guests/search/',
      data: { 'token': token },
      dataType: 'json',
      success: function(data) {
        console.log(data);
        $('#result').data('guest_id', data.id);
        $('#result #first_name_kana').html(data.first_name_kana);
        $('#result #last_name_kana').html(data.last_name_kana);
        $('#result #first_name').html(data.first_name);
        $('#result #last_name').html(data.last_name);
        if (data.family.length > 0) {
          $('#result_dialog').addClass('with-family');
          for (var i = 0; i < data.family.length; i++) {
            $('#result_dialog #family_list').append(
              '<li>' + data.family[i] + '</li>'
            );
          }
        }
        setTimeout(function() {
          $(document).on('keydown', numPadFunc);
        }, 1000);
        $('#result_dialog, .result-bg').show().addClass('show');
        var audio = new Audio('/media/audio/notification.mp3');
        audio.play();
      },
      error: function(response) {
        stype = 1;
        setTimeout(captureToCanvas, 1000);
      },
    });
  }

  function createVisitHistory(guestId) {
    var today = new Date();
    var datetimeString = dateFormat(new Date(), 'yyyy-mm-dd HH:MM:ss');
    var numberOfVisitor = parseInt($('.numpad .number-of-visitor .value').html());
    var formData = new FormData();
    formData.append('guest_name', guestId);
    formData.append('visit_date', datetimeString);
    formData.append('number_of_visitors', numberOfVisitor);
    formData.append('in_shop', 3)
    $.ajax({
      type: 'POST',
      url: '/new/history/',
      data: formData,
      cache: false,
      contentType: false,
      processData: false,
      success: function(data) {
        console.log(data);
        window.location = data['success_url'];
      },
      error: function(response) {
      },
    });
  }
</script>
{% block javascript %}
{% endblock %}
{% endblock %}

{% block css_generic %}
<link rel="stylesheet" type="text/css" href="{% static 'ceylontime/css/qr-identification.style.css' %}" />
{% block css %}
{% endblock %}
{% endblock %}

{% block sidebar-content %}
<div id="qr_scan_status" title="QRコードをスキャン">
  <img src="{% static 'ceylontime/images/qr-scan.png' %}" />
</div>
{% endblock %}

{% block content_generic %}
{% include 'snippets/qr_identification.html' %}
{% block content %}
{% endblock %}
{% endblock %}

ceylontime/templates/base_generic.html
{% load ceylontime_tags %}
<!DOCTYPE html>
<head>
    {% block title %}<title>Ceylon time</title>{% endblock title %}
    <meta charset="uft-8">

    {% load static %}

    <script type="text/javascript" src="{% static 'ceylontime/js/jquery-3.2.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'ceylontime/js/plugins/dynamic-search-box.plugin.js' %}"></script>
    {% block javascript_generic %}
    {% endblock %}
    <script>
      $(function() {
        if ($('.message-popup').length > 0) {
          $('.message-popup').addClass('wipe-in');
          var offset = -16 + -30 * $('.message-popup li').length;
          if ($('.message-popup').hasClass('close-by-button')) {
            var $closeButton = $('<div/>')
              .addClass('close-button')
              .on('click', function() {
                $('.message-popup').css('top', offset + 'px');
                setTimeout(function() { $('.message-popup').remove(); }, 4000);
              });
            $('.message-popup').append($closeButton);
          } else {
            setTimeout(function () {
              $('.message-popup').css('top', offset + 'px');
            }, 3000);
            setTimeout(function() {
              $('.message-popup').remove();
            }, 4000);
          }
        }
        $('.sidebar-wrapper .username').on('click', function() {
          $('.sidebar-wrapper .sidebar-nav').show();
          $('<div class="sidebar-background">').on('click', function(e) {
            e.preventDefault();
            $('.sidebar-wrapper .sidebar-nav').hide();
            $(this).remove();
          }).appendTo('body');
        });
        {% if user.is_authenticated %}
        $('#dynamic_search_box').dynamicSearchBox('{% url "ceylontime:guest-keyword-search" %}', '来店者氏名(カナ)を入力して検索');
        {% endif %}
      });
      function splitByCommas(num) {
          var str = num.toString().split('.');
          if (str[0].length >= 4) {
              str[0] = str[0].replace(/(\d)(?=(\d{3})+$)/g, '$1,');
          }
          if (str[1] && str[1].length >= 5) {
              str[1] = str[1].replace(/(\d{3})/g, '$1 ');
          }
          return str.join('.');
      }
    </script>

    <link rel="stylesheet" href="{% static 'ceylontime/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'ceylontime/css/plugins/dynamic-search-box.plugin.css' %}">
    <style>
      .message-popup {
        position: fixed;
        top: -64px;
        width: 100%;
        text-align: center;
        -webkit-transition: all ease-in-out 0.35s;
        -moz-transition: all ease-in-out 0.35s;
        -ms-transition: all ease-in-out 0.35s;
        -o-transition: all ease-in-out 0.35s;
        transition: all ease-in-out 0.35s;
        z-index: 100000;
      }
      .message-popup.wipe-in {
        top: 0px;
      }
      .message-popup ul {
        display: inline-block;
        width: 100%;
        padding: 7px 16px;
        text-align: center;
        white-space: nowrap;
        background-color: #E1F5FE;
        background-clip: padding-box;
        border: 1px solid #29B6F6;
        box-shadow: 0 3px 12px rgba(0,0,0,0.15);
        font-size: 0.9rem;
        list-style: none;
      }
      .message-popup.error ul {
        background-color: #FCE4EC;
        border: 1px solid #C2185B;
      }
      .message-popup ul li {
        padding: 4px 0;
        color: #0288D1;
      }
      .message-popup.error ul li {
        color: #911;
      }
      .message-popup .close-button {
        position: absolute;
        right: 8px;
        top: 8px;
        background-color: rgb(224, 183, 197);
        width: 24px;
        height: 24px;
        border-radius: 12px;
      }
      .message-popup .close-button::before {
        content: '';
        position: absolute;
        width: 18px;
        height: 3px;
        background-color: #FCE4EC;
        border-radius: 1.5px;
        transform: rotate(45deg);
        left: 3px;
        top: 11px;
      }
      .message-popup .close-button::after {
        content: '';
        position: absolute;
        width: 18px;
        height: 3px;
        background-color: #FCE4EC;
        border-radius: 1.5px;
        transform: rotate(-45deg);
        left: 3px;
        top: 11px;
      }
    </style>
    {% block css_generic %}
    {% endblock %}
</head>

<body>
    {% if messages %}
    <div class="message-popup {{ messages|message_level }}">
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}
    <header>
        <div class="content">
          <a class="logo-link" href="{% url 'ceylontime:home' %}"><img class="logo" src="{% static 'ceylontime/images/logo.png' %}" alt="Ceylon time guest checker"/></a>
          {% if user.is_authenticated %}
          <span id="dynamic_search_box"></span>
          {% endif %}
          <div class="col-sm-2 sidebar-wrapper">
            {% block sidebar-content %}{% endblock %}
            {% if user.is_authenticated %}
            <span class="username">{{ user.get_username }}</span>
            {% block sidebar %}
            <ul class="sidebar-nav">
              <li><a href="{% url 'ceylontime:home' %}">ホーム</a></li>
              <li><a href="{% url 'ceylontime:new-visit' %}">新規来店登録</a></li>
              <li><a href="{% url 'ceylontime:guest-list' %}">顧客一覧</a></li>
              {% if perms.ceylontime.add_dmtemplate %}
              <li><a href="{% url 'ceylontime:dm-template-list' %}">DMテンプレート管理</a></li>
              {% endif %}
              {% if perms.ceylontime.add_dmhistory %}
              <li><a href="{% url 'ceylontime:dm-setup' %}">新規DM送信</a></li>
              <li><a href="{% url 'ceylontime:dm-list' %}">DM送信履歴</a></li>
              {% endif %}
              <li><a href="{% url 'account_logout'%}?next={{request.path}}">サインアウト</a></li>
            </ul>
            {% endblock sidebar %}
            {% else %}
            <span><a href="{% url 'account_login'%}?next={{request.path}}">Signin</a></span>
            {% endif %}
          </div>
        </div>
    </header>
    <div>
    <!-- TODO create searching box -->
    </div>

    <div class="col-sm-10 content main">
        {% block content_generic %}{% endblock %}
        {% block pagination %}
          {% if is_paginated %}
              <div class="pagination">
                  <span class="page-links">
                      {% if page_obj.has_previous %}
                          <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                      {% endif %}
                      <span class="page-current">
                          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                      </span>
                      {% if page_obj.has_next %}
                          <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                      {% endif %}
                  </span>
              </div>
          {% endif %}
        {% endblock %}
    </div>

</body>